# Generated by Django 4.2.20 on 2025-04-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_admin'),
    ]

    operations = [
    ]
